### ISSUE TITLE
Allow assigning Static IPs to clients

### ISSUE THREAD

**Issue by ssamjh** [angristan/openvpn-install#113]
It would be a nice feature for setting up server to server vpn connections.

**Comment by Leopere** [comment]
Realistically you already have one part of this already completed you'd just need to figure out how to install a client on the CLI and then make sure you don't lock yourself out of your own VPS/Server in the process while you restrict traffic.

**Comment by cezar97** [comment]
Clients already have static IP's.

You can find them in 
```/etc/openvpn/ipp.txt```.

**Comment by angristan** [comment]
@cezar97 Yes but what about editing them? Restarting OpenVPN removes the modification I made

Edit: found the answer: https://serverfault.com/a/826710/405096.

Now should we really add a way to enable and manage this in the script ? Linking people to this issue may be enough, as this is a specific use case.

For instance we could add this to a FAQ in the README or even a wiki.

**Comment by cezar97** [comment]
> Edit: found the answer: https://serverfault.com/a/826710/405096.

In that case he uses the same certificate for all devices so, as someone else there said, we can use the `client-config-dir` on server side.

A well documented tutorial [here](https://zeldor.biz/2011/05/openvpn-road-warrior-setup/) explains better this type of setup. Also from the same site:
>
```
# Maintain a record of client <-> virtual IP address associations in this file.
ifconfig-pool-persist ipp.txt
```
So that's what ipp.txt does :smile: (#56).

> For instance we could add this to a FAQ in the README or even a wiki.

As the FAQ entries wouldn't be a lot (assign static ip to clients [this issue], accessing local services via openvpn [issue 142], listen on multiple port [issue 43], encrypted .ovpn [issue 9] ...) and as the answer is the link with the respective issue in my opinion the README should be just fine. Obviously a wiki is far better but it requires a little more work.

> Linking people to this issue may be enough, as this is a specific use case.

I agree.
