### ISSUE TITLE
Add support for DNSCrypt

### ISSUE THREAD

**Issue by LukaTCE** [angristan/openvpn-install#122]
Hi please add support for DNS service for DNSCrypt it will be making VPN even more secure.
https://dnscrypt.org/

**Comment by angristan** [comment]
Wouldn't this be more relevant? https://github.com/Angristan/OpenVPN-install/issues/5

**Comment by Leopere** [comment]
You'd likely need to add the client to the host which adds complexity to this install which may be out of scope.  Granted I would like this also I'm just saying that it might be out of scope.

However, the added benefit to obfuscating why you're visiting various IP addresses would absolutely help with increasing privacy.  DNS is one of those things you want performant but you also don't really want people creeping on your traffic either and who/what/why you're visiting is your business not your ISP's or quite frankly anyone in-between.

Maybe a secondary script that could be maintained along side of this one and maybe even called by this one could be warranted.

What I've always thought would be ideal is running your own personal server and client at the same time but maybe that's silly.  This way your DNS queries stay 100% local.

**Comment by angristan** [comment]
> You'd likely need to add the client to the host which adds complexity to this install which may be out of scope. Granted I would like this also I'm just saying that it might be out of scope.

Agreed.

Also, as [DNScrypt is abandoned](https://www.reddit.com/r/linux/comments/7owb1s/psa_dnscrypt_is_now_abandoned/), I'm closing this. Hoepfully we'll be able to use DNS-over-TLS soon.

**Comment by loadcorp** [comment]
> Also, as DNScrypt is abandoned

What about now? https://github.com/jedisct1/dnscrypt-proxy last update about 4 days ago or I missing something?

Maybe existing another way for DNS encryption on own OpenVPN server?

**Comment by cezar97** [comment]
There's also an interesting WIP here: http://odns.cs.princeton.edu/ but it's only at an early stage.

**Comment by Leopere** [comment]
I think that our eventual goal should be to decide if we want this to prevent or at least help eliminate unintentional leakage.  Then maybe publish a section stating what will likely still leak regardless of our efforts here.

DNS queries should be encrypted entirely so that only you and your DNS server knows what's happening there should be no simple path between eavesdroppers and your traffic.  My own goals are to have next level privacy protections without significant cost to my convenience then maybe one day I'll write a blog or something about it.  

There is an RFC for this https://tools.ietf.org/html/rfc7858 which may eventually be possible; I think that Quad9 is primed to provide it as part of their service asap if not already.  I could be out of date with this information.

**Comment by cezar97** [comment]
@chamunks as some people aren't aware of, encrypting DNS queries doesn't improve privacy. Why? Because you are relaying on an ISP, or vps provider. So in fact they can't get your browsing history by looking at the dns queries but looking at the traffic port 80/443. From this point of view encrypting dns queries only makes things relatively harder but not impossible.
Again, DNS over TLS only protects queries from being modified by an attacker, kind of DNSSEC.
Regarding quad9, from their faq:
> We do support DNS over TLS on port 853 (the standard) using an auth name of dns.quad9.net.

**Comment by Leopere** [comment]
Sounds like DNS over TLS its just signing the queries.  Ideally, you'd want full obfuscation of the DNS queries to third parties.  It's quite frustrating that DNS queries are being used against you these days, but I guess it was inevitable.  

Caching your DNS queries through the local unbound process is going to help decrease DNS leaks significantly.  However, you still expose whatever DNS queries are coming out of the VPN machine to wherever you're getting your upstream information.  Ideally, you want the relationship from your device to wherever you're getting the information entirely secured and assured against tampering.

**Comment by cezar97** [comment]
> Sounds like DNS over TLS its just signing the queries.

In theory is more than that: a secure channel is established and all the data passed can't be eavesdropped...
> Ideally, you'd want full obfuscation of the DNS queries to third parties.

...In practice encrypting dns queries does not prevent from seeing people's browsing history. You can still watching for traffic on ports 80/443 and have all the visited sites ( dns queries encryption / obfuscation is useless here ). So this was what I tried to explain.

**Comment by Leopere** [comment]
True enough thanks for the clarity and yes that's what I'm aware of as well.  The situation, however, is it removes a vector for proving intent.  The encrypted https packet would go a different route as well then the DNS packet so the DNS packet would be encrypted so that you can't see where you're going to be sending packets.  DNS is just a point of concentrated data collection ability.  If you can take steps to make that difficult, you remove a vector.  

It is indeed not a 100% fix.  The situation is that basically running your own VPN is to choose exactly where your data egresses and helps decentralize this sort of function.

**Comment by Leopere** [comment]
Ah, I see why you're saying that now.  I stopped using my own ISP's DNS over a decade ago due to reliability issues, but yes you're right all it takes is for someone to sit at my ISP and listen in.  

Which is why I personally would love to be able to encrypt my data over the pipe to the DNS provider.  I don't want to have to trust my ISP basically.

**Comment by iProdigy** [comment]
DNSCrypt is not necessary at the client-level when no leaks are occurring; DNS requests are forwarded to the VPN server and cannot be intercepted by the clients' ISP. 

On the other hand, DNSCrypt could be used at the host-level to add another layer of obfuscation, making it harder for hosting providers from watching/hijacking DNS queries.
