### ISSUE TITLE
Openvpn client not connecting to server

### ISSUE THREAD

**Issue by Gpette01** [Angristan/OpenVPN-install#1249]
### PROBLEM
I installed openvpn through the script and created a client, I used all the default parameters and I have also did port forwarding to my server for all the nessescary openvpn ports, when I try connecting through opevpn on my local network I get this error: 

- 2024-10-05 01:07:49 read UDPv4 [ECONNREFUSED]: Connection refused (fd=3,code=111)

When i try using openvpn2 or openvpn3 it just gets stuck on connecting:
(example for openvpn2)

- 2024-10-05 01:08:45.530655 [STATUS] (StatusMajor.CONNECTION, StatusMinor.CONN_CONNECTING) 

When i try outside of my local network openvpn just TLS handshake fails after 60 seconds, openvpn2 and 3 just get stuck on connecting.

When I use the command: ncat -u -v <public_ip> 1194
Ncat: Version 7.94SVN ( https://nmap.org/ncat )
Ncat: Connected to <public_ip>:1194.
This works on both inside and outside of LAN which shows that port forwarding is correct and also openvpn server is listening

### STEPS I TRIED TO RESOLVE THE ISSUE

- Reinstalling the server with tcp/udp
- Tried both public Ipv4 and local but the correct it's having the public ip address on the remote

- On the client side tried using openvpn, openvpn2, openvpn3
- Tried differently generated client files, with password and passwordless

I am not sure what exactly to search for or go through to solve the issue since ncat shows that it connect

**Comment by SSoBad** [comment]
same problem, does anyone have a solution?

**Comment by giuuuug** [comment]
I've the same problem.

**Comment by SSoBad** [comment]
What I tried to do:

- Checked open ports via `ss -tunlp`

- Checked routes and iptables rules, comparing them with the existing working configuration using the same script

- Along the way I discovered that the site for checking external ip does not work

In my opinion, everything looks exactly the same as in the working configuration.

Upon request, I can provide the configuration of my server, because I don’t know where to dig anymore, but still I think that there is a problem in routing, because after connecting, my pings only reach the VPN server

**Comment by Gpette01** [comment]
So after a throurough search on what the problem is with a friend of mine who actually set it up this way the only difference he made it was that the vpn was setup on server where the server was provided via a service, you know those online servises that provide servers we got to the following:

- Do not use the default opnevpn port 1194 use something else 
- Use sudo openvpn --config /etc/openvpn/server.conf to check if everything on the server side is okay
- On the server.conf add on the last line client-to-client
- Lastly the port forward for my ISP did not work becuase they dont allow port forwarding, I have yet to try on a server but i can only assume that it would work

**Comment by SSoBad** [comment]
> So after a throurough search on what the problem is with a friend of mine who actually set it up this way the only difference he made it was that the vpn was setup on server where the server was provided via a service, you know those online servises that provide servers we got to the following:
> 
> * Do not use the default opnevpn port 1194 use something else
> * Use sudo openvpn --config /etc/openvpn/server.conf to check if everything on the server side is okay
> * On the server.conf add on the last line client-to-client
> * Lastly the port forward for my ISP did not work becuase they dont allow port forwarding, I have yet to try on a server but i can only assume that it would work

Interesting comment, I also have a virtual server, now I’ll try to do what you described. 

I'll post the results here.

**Comment by Gpette01** [comment]
Another problem i had is that server.conf did not find the keys, the solution i found to this is to edit the server.conf and do a specific path there for exmaple /home/<user_name>/keys/<key_name>

**Comment by SSoBad** [comment]
I created a new server with your parameters and attached the config below.

As a result, the VPN still doesn’t work. In addition to the theory about the port and traffic, I switched to TCP and selected a random port, but there was no effect.

Next about the comment with incorrect key paths. Relative paths are specified in the config, so it is important where you run the check, run from the `/etc/openvpn` directory and it will pass. Most likely, if the config was incorrect, the service would not start.

Apart from this, there would be no talk about connecting a client to such a server, and let me remind you that they exchange keys perfectly, it’s just that nothing else works. 

I discovered one more feature: on the working server, the address of the tunnel adapter is pinged, unlike the new instance. Even after adding the `client-to-client` option, the address did not work.

While I was digging around with the settings, I discovered that the kernel variable that is responsible for forwarding is missing in sysctl, despite the fact that other variables were added from the script, apparently it is added somehow differently, since I still found it in the kernel:

```
# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

My server.conf:
```
port 65042
proto tcp6
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "redirect-gateway def1 bypass-dhcp"
server-ipv6 fd42:42:42:42::/112
tun-ipv6
push tun-ipv6
push "route-ipv6 2000::/3"
push "redirect-gateway ipv6"
compress lz4-v2
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
crl-verify crl.pem
ca ca.crt
cert server.crt
key server.key
auth SHA256
cipher AES-128-GCM
ncp-ciphers AES-128-GCM
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
client-config-dir /etc/openvpn/ccd
status /var/log/openvpn/status.log
verb 3
client-to-client
```

My iptables:
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i ens3 -p tcp -m tcp --dport 65042 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A FORWARD -i tun0 -o ens3 -j ACCEPT
-A FORWARD -i ens3 -o tun0 -j ACCEPT
```
and
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o ens3 -j MASQUERADE
```

my `ip a`:
```2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether brd ff:ff:ff:ff:ff:ff
    inet /32 brd  scope global ens3
       valid_lft forever preferred_lft forever
    inet6 scope global 
       valid_lft forever preferred_lft forever
    inet6 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq state UNKNOWN group default qlen 100
    link/none 
    inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6  scope global 
       valid_lft forever preferred_lft forever
    inet6  scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

my vpn route on server:
```
10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.1
```

**Comment by Gpette01** [comment]
Honestly I've got no idea what could be the issue, I've had many similar problems to the ones you described but neither did I manage to get it up and running, my friend who got it working did the exast same steps as us nothing different but for some reason it worked which is weird so yeah, one thing you can check though as when I had a key problem the server log did not show any error about the keys is check the permission for them or who owns the keys, for example the tls key should probably be owned by the root and have chmod 600 permissions

**Comment by SSoBad** [comment]
I spent a lot of time on the topic to understand at least some clue, and it appeared. I used tcpdump, trace and ping. I can definitely say that the packets leave me and reach the server. The following packets are not applied to the tunnel adapter, although when I ping it, in fact, it should... Then I noticed an interesting situation, when the client reconnects the packets, they still reach the adapter settings and pings mechanically, but I could not understand why this happens.

Anyway, I contacted support and asked for a new address, if it works on this one, I'll definitely let you know

**Comment by Gpette01** [comment]
Okay so I created a virtual server on cloudlab, upload the installation script, runned it created a random port, added client-to-client on the server.conf also changes the keys instead of just being a key to have a path for example tls-crypt /path/to/the/key  runned it manually via that command sudo openvpn --config /path/to/server.conf and it worked

**Comment by SSoBad** [comment]
> Okay so I created a virtual server on cloudlab, upload the installation script, runned it created a random port, added client-to-client on the server.conf also changes the keys instead of just being a key to have a path for example tls-crypt /path/to/the/key runned it manually via that command sudo openvpn --config /path/to/server.conf and it worked

I installed a cooler VPN on my host with problems, everything works fine. Based on the answers from the hosting provider, I realized that this is due to blocking, so I recommend simply changing the protocol to a less poppy one.

At this point I would close the discussion, as it is obvious that this is not a problem with the script itself.

**Comment by Gpette01** [comment]
I agree well i hope this is usefull to anyone who finds this conversation!
