### ISSUE TITLE
Mobile device only

### ISSUE THREAD

**Issue by simplecode678** [angristan/openvpn-install#140]
Hi,
Can anyone please let me know how to make it works on mobile devices only ? What should i change ?
thanks !
Raz

**Comment by angristan** [comment]
@simplecode678 I don't understand what you mean... What's the point of doing this?

**Comment by simplecode678** [comment]
Hi ! in some situations people will abuse of the VPN, target is to make vpn only works on mobile devices.

**Comment by angristan** [comment]
Only people to whom you give access to the VPN will be able to use it 🤔

**Comment by simplecode678** [comment]
Just a simple question i was asking myself, but it seems that i'm the only one to think that may be interesting in some kinds of situations ;) Thanks !

**Comment by simplecode678** [comment]
i have checked syslog
Dec 20 15:57:11 guest ovpn-server[2624]: XXX.XXX.XXX.XX:37984 peer info: IV_PLAT=win
informations are coming from --push-peer-info
so if anyone has an idea  to filter clients by OS please ?

**Comment by Leopere** [comment]
@simplecode678 I doubt that OpenVPN really has this since you control 100% of who has access to the Private keys that you distribute.  This script appears to mostly be for personal use anyways, I wouldn't recommend using it for some kind of semi public / production release as you should probably know about how your VPN works if you're deploying it into a production environment.  That said it does seem like a cool feature.

**Comment by simplecode678** [comment]
@chamunks  you're right it should be nice, but for now i give up too complicated :)
