### ISSUE TITLE
Accessing local services via OpenVPN

### ISSUE THREAD

**Issue by benbristow** [angristan/openvpn-install#142]
Excuse my amateurness with OpenVPN. I've tried Googling around but not sure how to resolve this.

I'm wondering if there's a way to access local services via the OpenVPN server configured by this script.

**Current situation:**

* Server is at Home B
* Client (me) is at Home A.
* If I'm connected to VPN and try and access a local server (e.g. router) at 192.168.0.1, I get the router of Home A (client) and not Home B (server)

**What I'd like:**

* Server is at Home B
* Client (me) is at Home A
* If I'm connected to VPN and try and access a local server (e.g. router) at 192.168.0.1, I get the router of Home B (server) and not Home A (client)

I can't access other servers either, e.g. 192.168.0.200 (a Samba server).

I've tried modifying my server.conf file to no avail. Is there an easy solution to solve this dilema?

Thanks

Ben

**Comment by orazioedoardo** [comment]
Having the same subnet on both the remote and local network causes confusion for the client. You need to change your local subnet to something less common.

**Comment by ghost** [comment]
As @orazioedoardo pointed out, if you have the same subnet on the client and on the server then by default the traffic to that subnet will not be routed through the vpn but through your home router.

To avoid that you can add the following line in your .ovpn profile `route-up "/sbin/ip route add 192.168.0.0/24 via 10.8.0.1"` or by doing it manually via terminal once connected: `sudo route add -net 192.168.0.0/24 dev tun0`.

**Comment by ghost** [comment]
@benbristow It can be done also on server side. Just add `local` here so it looks like the following:
`push "redirect-gateway local def1"`.

EDIT: This should work on Windows, too.

Reference: [OpenVPN Documentation](https://openvpn.net/index.php/open-source/documentation/howto.html).

**Comment by cezar97** [comment]
As the solution is confirmed to work in #185, this issue can be closed. @Angristan

**Comment by HarvsG** [comment]
So if I installed the set up on a raspberrry pi at home and simply added `push "redirect-gateway local def1"` to the server config, would I be able to access all my local resources as if I was at home, eg mediaservers, casting, spotify connect, network printers etc etc. 

Or is there more configuration that I would need to do?

**Edit**: Everywhere else is saying that in order to get this functionality I would need something called TAP/Bridge mode?

**Comment by cezar97** [comment]
Hi,
you don't have to add that line, there's already there. The only addition you have to do is that `local` in that line, the one with ``

**Comment by ghost** [comment]
Hi @harvsg,
you don't have to add that line, it's already there. The only addition you have to do is `local` in that line, the one with `push redirect-gateway` indeed.
If you have a Bridged Setup, then all of this works out of the box. With NAT, or TUN, you have to change the config as explained above to make this work, but the result is the same: accessing PCs on the VPN's LAN. On the other side, this also means that every time you ping 192.168.0.2, for example, the PC's with this IP on the VPN's LAN will respond and not the one that's on the network you connect from.
BTW, if the network range are different on server and client, then the traffic is correctly redirected to the VPN's LAN without any configuration. The `local` is only if you connect from a 192.168.6.1/24 network to a 192.168.6.1/24 one, so ones with the same subnet. Indeed, @benbristow says that accessing 192.168.0.1 would have the home's router and not the VPN's ( as said, because of same subnet ).
