### ISSUE TITLE
DNS Leaks

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#149]

**Comment by shrumit** [comment]
In order for this to work correctly, the following needs to be done:

1. Comment out the line `setenv opt block-outside-dns`. This is nonsense to bash and will cause errors.

2. Ensure that `/etc/openvpn/update-resolv-conf.sh` exists. On my system (Ubuntu 16.04, OpenVPN 2.3.10) the actual filename was `/etc/openvpn/update-resolv-conf`. Append the lines in the above comment to your `client.ovpn`.

3. Do not use the network-manager-openvpn package. You must use the command `openvpn --config client.ovpn` to reliably start your VPN session on Ubuntu. There is [a bug open since 2013](https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1211110) that prevents `update-resolv-conf` or any external script invoked from the .ovpn config file from running when you connect through NetworkManager.

4. When you do all the above steps correctly, you will see that the output of `cat /etc/resolv.conf` shows the nameservers taken from the OpenVPN server. However, these are *prepended* to whatever you had before, which is still a security risk, since if a DNS request fails at the preferred nameservers, they will fall through to the local ones.

Needless to say, running OpenVPN as a client on Ubuntu  is an absolute sh*tshow.

**Comment by cezar97** [comment]
I opened an issues just because DNS leaks are a common problem for most devices.

Thank You for point 4! I didn't tried to look at the `/etc/resolv.conf` to see the DNS once connected. 

> if a DNS request fails at the preferred nameservers, they will fall through to the local ones.

Using a local DNS resolver on the VPN should solve this.

**Comment by coldtelling** [comment]
I also got dns leaking

**Comment by Kcchouette** [comment]
I have the same problem than @cezar97.
I don't understand why the bug is closed, as it's at the moment still unfixed

**Comment by cezar97** [comment]
Well, I closed it as it isn't related to the script itself.
Anyway following the above steps ( run from terminal, setting `up` and `down` scripts and check the `resolv.conf` to see that the DNS of the VPN is first ) solved it for me.
I've also cross-referenced the PR where, on the Local-Dns-Resolver repo, instructions on how to check for dns leaks were added.

**Comment by iProdigy** [comment]
> Using a local DNS resolver on the VPN should solve this.

- cezar97

**Comment by Kcchouette** [comment]
Oh, so it's related to #5 

For me, `up` and `down` seems not working, as `resolv.conf` is not modified by new DNS.
I have take the script from [here](https://github.com/masterkorp/openvpn-update-resolv-conf/blob/master/update-systemd-network.sh) as Ubuntu 18.04 seems to ship a new version that is compatible with something (`Too few arguments`)

**Comment by cezar97** [comment]
> I have take the script from here as Ubuntu 18.04 seems to ship ...

That's why I linked those resources. I'll update my answer for Bionic, then.

**Comment by Kcchouette** [comment]
Thank you. I'll test the `update-systemd-resolved` fix.

Edit: here the solution:

1. Check which file is put in `/etc/openvpn/`
2. Adding that at the end of your `.ovpn` file:
```
script-security 2
up /etc/openvpn/<name_of_the_file>
down /etc/openvpn/<name_of_the_file>
```
3. Edit `/etc/nsswitch.conf`, the line *hosts* should be like that:
```
hosts: dns
```
(I didn't arrive to use the *systemd-resolved* daemon, it's why I remove *resolve*)
4. You can start your vpn: `sudo openvpn --config <.ovpn>`

**Comment by ghost** [comment]
I also had this problem, but the what I found was that _resolveconf_ wasn't installed.
My config:
```script-security 2
up /etc/openvpn/update-resolv-conf 
down /etc/openvpn/update-resolv-conf
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"```
