### ISSUE TITLE
Google Auth integration

### ISSUE THREAD

**Issue by timgurney-ee** [angristan/openvpn-install#21]
Instead of using a password on the cert, I am interested in using google auth tokens, is there any plan or simple tweak for this ?

**Comment by atulsian89** [comment]
@timgurney-ee  Could you try this? I will be trying it out next week.

https://vorkbaard.nl/setup-openvpn-with-google-authenticator-on-ubuntu-12-04-lts-server/

or 

https://www.howtoforge.com/securing-openvpn-with-a-one-time-password-otp-on-ubuntu

**Comment by timgurney-ee** [comment]
@atulsian89 - thanks for the links, I have done it manually before, and I might fork the script and try adding it in, just think it would be a nice addition to the script.

**Comment by CyberCam1969** [comment]
So anyone been successful in integrating google authentication.

**Comment by cezar97** [comment]
I've tried Digital Ocean's Tutorial at the following link [MFA for SSH on Ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04).

It works very well, but there is one problem not listed there. You can login with all the users out of the box, but to login with root, as some vps have root account only by default, you have to modify the next line in `/etc/ssh/sshd_config`:

`PermitRootLogin prohibit-password` => `PermitRootLogin yes`.

Even if I login with private key and the TOTP generated key I need to do this change, otherwise the TOTP key fails. I don't know however how are they related, as TOTP isn't properly a password.

PS: For Security Reasons it's better to leave it to `PermitRootLogin no`, create a new user account, add it to the sudoers file and login with it.

**Comment by craig-mld** [comment]
+1

**Comment by Leopere** [comment]
How would you even use Google authentication with Viscosity or any of the other OpenVPN clients?  Isn't it just a better policy to just not let your private key get lost to some rando?

**Comment by cezar97** [comment]
@timgurney-ee it would be a nice addition indeed, but at what cost?
Openvpn renegotiate the keys every hour so this way you're asked for the token again. There are workarounds for this but I don't recommend them: I'm referring at disabling renegotiation so that once connected you have the same keys until you disconnect no matter how much time ( days etc. ) your session is old.
Plus, for what I understand, there's still the fact that with Google-authenticator, or whatever you use, you must have a local UNIX account for every profile / user and that's not very convenient or what this script should do ( in my opinion ).
In the future I'll take into consideration writing how to do it on the wiki. Thank you for the suggestion!
