### ISSUE TITLE
Opening a port

### ISSUE THREAD

**Issue by aquada** [angristan/openvpn-install#224]
Nice script. Worked flawlessly for me. 

Can you advise how I would open up a port for torrent access please?

thanks

**Comment by angristan** [comment]
What do you mean by torrent access?

**Comment by aquada** [comment]
Setting up transmission I need to select an open port to allow traffic through. So I would like to open a specific port on the server for this purpose. 
Daniel

**Comment by cezar97** [comment]
When you connect to the openvpn server set up by this script, then you're behind NAT and you have to use iptables to forward the port on the server machine. If then the server is also behind NAT, port forward that also on the router.
Another approach is configuring the openvpn server with a TAP interface ( aka bridge setup ) so the connected client gets a IP on the server's private network and so just port forward on the router next. ( I'm talking about router because I'm assuming that the openvpn server is behind NAT, so on a home LAN otherwise with a public IP it's not necessary ).

**Comment by angristan** [comment]
I've never had to open any port for a torrent client, including transmission...

**Comment by cezar97** [comment]
@Angristan actually it happens on many softwares that you have to open ports just to improve speed, as it's optional by default and not necessary like you said.

**Comment by aquada** [comment]
The servers on a public network.  I'm having trouble with the tables. I tried this example where 192.168.1.2 is the public network, but the 6688 still showed as closed at the client. Maybe the example is wrong or do I need to apply something. I've used UFW, but not done much with iptables. Any help appreciated. 
```
iptables -A PREROUTING -t nat -i ens3 -p tcp --dport 6688 -j DNAT --to 192.168.1.2:6688
iptables -A FORWARD -p tcp -d 192.168.1.2 --dport 6688 -j ACCEPT

```

**Comment by cezar97** [comment]
I can't test it, but here's what I've found:
try first answer + its comments from https://serverfault.com/questions/834566/port-forwarding-with-openvpn.
Or the first answer from https://unix.stackexchange.com/questions/55791/port-forward-to-vpn-client.
After changing, flush iptables and list the rules to make sure they're active.
BTW, it seems to me that in the rules you just pasted the first one has `--to 192.168.1.2:6688` instead the openvpn client ip `--to 10.8.0.x:6688`. Maybe that's why it doesn't work.

**Comment by aquada** [comment]
@cezar97 thanks :) correct rules were as you said (x.x.x.x is public and 10.8.0.2 is the client VPN address)
```
iptables -A PREROUTING -t nat -i ens3 -p tcp --dport 6688 -j DNAT --to 10.8.0.2:6688
iptables -A FORWARD -p tcp -d x.x.x.x --dport 6688 -j ACCEPT

```

It would be really cool if this was added as an option on the menu

**Comment by aquada** [comment]
Just a quick question. How do I make these rules persistent? I see you have the rules in /etc/iptables/iptables.rules. I tried iptables-save, but that didn't work.

**Comment by cezar97** [comment]
To make it persistent once everything works do `iptables-save > /etc/iptables/iptables.rules`.
> It would be really cool if this was added as an option on the menu.

I'll consider this when I'm going to have more free time. At the moment we had a lot of requests of tweaks like this one.

**Comment by LeksN** [comment]
hello could you add to your script the ban of ping following the example of these rules iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
iptables -A INPUT -i eth0 -p icmp --icmp-type echo-request -j DROP
