### ISSUE TITLE
Activation of openvpn seems to fail - Error block-outside-dns

### ISSUE THREAD

**Issue by knowhowseeker** [angristan/openvpn-install#254]
I load openvpn after having completed openvpn-install.sh. I do that in PuTTY and PuTTy stops after mentioning Rout_Gateway and my IP Adress. After that I cannot connect to the server with PuTTY anymore. The first line "... block-outside-dns" reads like an error. Sorry I have no clue how to proceed.
Thanks for some help.

![image](https://user-images.githubusercontent.com/41070573/42526399-fc35c63c-8475-11e8-809e-ea0f677c25ac.png)

**Comment by cezar97** [comment]
Hi, ignore that error. It's an option that works only on Windows, but that's Linux so it doesn't know it.
Regrading your problem, once you connect to the VPN all the server connection goes through the VPN so you loose ssh connection. If you want to connect to it again you have 2 options:
You connect to the VPN and ssh into the server with its VPN IP that seems to be 10.8.0.2.
You reboot the server to disconnect from the VPN and ssh again. Then add the following to your server config: `route <VPN IP> 255.255.255.0 net_gateway`.
I recommend you the second one because you esclude your server IP to use the VPN so it is never routed through it.
Here's more info about that: https://superuser.com/questions/487760/openvpn-exclude-ip-or-port.

**Comment by knowhowseeker** [comment]
Thanks, that worked just fine.
