### ISSUE TITLE
Please add support AlpineLinux

### ISSUE THREAD

**Issue by butaford** [angristan/openvpn-install#259]
Please add support AlpineLinux
Need install packages for run script:
`apk add bash ca-certificates gnupg openvpn iptables openssl wget ca-certificates curl easy-rsa sed coreutils`
Support tun kernel
```
modprobe tun
echo "tun" >>/etc/modules
```
or tap
```
modprobe tap
echo "tap" >>/etc/modules
```

**Comment by angristan** [comment]
Clearly out of scope since it's not used much outside of Docker containers. If a good PR is made, we will consider supporting it. Until then it's not worth the time, sorry.

**Comment by randshell** [comment]
So there isn't going to be a Docker image?
There are already a lot of them for openvpn, but they don't have the same goals as this script 😉

**Comment by angristan** [comment]
@randomshell nope

**Comment by vahidshirvani** [comment]
I have the script running in docker. Please see https://github.com/vahidshirvani/openvpn-install

**Comment by Xavery9** [comment]
Sorry for digging it out
A few years passed and Alpine became a great solution for tiny standalone servers, not only containers. In my opinion it's better to have support for Alpine than for example Oracle Linux. 
Otherwise your great script might be easier to make it portable if it hadn't huge parts responsible for package installation. This can be done manually.
Regards
Grzegorz
