### ISSUE TITLE
All traffic being routed over VPN

### ISSUE THREAD

**Issue by ejbolt** [angristan/openvpn-install#267]
Hi,

I'm using OpenVPN to access network resources at my house when I'm elsewhere, and my ISP provides terrible upload speeds (Gigabit download though!), so I only want traffic going to my home network to be routed over the VPN.

Client config is:
client
proto udp
remote *** 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name *** name
auth SHA256
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
verb 3
`

Private info replaced with ***

Any help would be appreciated!  Have googled the issue for days but no offered solution has worked.

**Comment by cezar97** [comment]
Hi,
If the two networks, yours and the one from the VPN, are on different subnets ( example 192.168.0.1/24 and another on 192.168.1.1/24 ), then remove the line `push "redirect-gateway def1"`.
If they are on the same subnet, instead of removing try to edit it to: `push "local"`.
After, for make DNS work, edit the first `push "dhcp-option DNS x.x.x.x"` to your router IP, the one from your VPN ( this is optional ).

**Comment by ejbolt** [comment]
I'll give that a try!  The current options work fine for windows.  The
problem is only in Linux, which I can work around by using network managers
openvpn plugin and editing the connection through the GUI. But I'll try
this when I get home.   I'd like it to just work without editing options
after importing the client config :).  Awesome setup script btw.  Worked
like a charm on my fedora box

**Comment by angristan** [comment]
Thanks for the answer @cezar97
