### ISSUE TITLE
Traffic are not all being route

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#447]
Hi,

I install openvpn using the last script and got some issue when trying to access site or using local app.

I'm using ArchLinux on both client and server side.
Using my normal browser I can see than my IP got the server one (IPV4 or IPV6 are working)

On the server nothing was change same for client side.
I use the command openvpn `sudo --config vpnfile.ovpn` to connect to my vpn server.

When I try for example accesing site that are allowing only my IP or when I try use local app that allow my IP to access them it still use my local IP and not the one I openvpn assign me.

Is there something i need to change client side to force the use of tun0?

**Comment by angristan** [comment]
When you go on websites like https://www.ipalyzer.com/ or https://ipleak.net/ which IP do you see? The server's or your router's?

[This](https://github.com/angristan/openvpn-install/blob/dea1d6db2b6611b88d7b4e94f014621fb2ad4cec/openvpn-install.sh#L754) should overwrite your gateway. What does `ip route` says?

**Comment by fleekix** [comment]
This issue is something similiar to mine. When client connects to the VPN I the public ip changes as expected, but there are resources on the LAN which I want to get into remotely that do not respond. For example if I want to log into my freenas web interface I am unable to. Pings DO work but no other protocols seem to. Any thoughts? Is this just a routing issue?

**Comment by fleekix** [comment]
I forgot to mention my goal for using this vpn is to have 1 encrypted link to my home lan so that I don't have to have ports forwarded too much. For things like nextcloud syncing and whatever else.
