### ISSUE TITLE
CentOS easy-rsa issue

### ISSUE THREAD

**Issue by mrkuddlez** [angristan/openvpn-install#463]
I'm new to linux and trying to set up openvpn so very sorry if I did something dumb and didn't realize.

I'm on CentOS 7.

At the end of the script I get
"openvpn-install.sh: line 986: cd: /etc/openvpn/easy-rsa/: No such file or directory"
in the command line and the script does not generate a config file. 

I hope someone can help, thank you!

**Comment by angristan** [comment]
Can you start from scratch and run the script with `bash -x openvpn-install.sh`?

**Comment by mrkuddlez** [comment]
Done,
https://pastebin.com/q6pigkpw
I replaced my servers ip with "ip" in the pastebin for privacy reasons but if that caused an issue I could try to send it to you privately.

Thanks for the quick response sorry it took me a second to figure everything out, and sorry in advance if I just made a stupid mistake.

Thanks.

**Comment by angristan** [comment]
Thanks, I guess there really is an issue with this part of the script on CentOS, I'll take a look.

**Comment by skepticnibble** [comment]
The $OS var isn't getting set in checkOS() because it's matching the file exists (really just a sym link) check for /etc/system-release which only supports "amzn".  Since "OS=centos" is never set, the openvpn packages (and other deps) never get installed via installOpenVPN().  Just need to re-order the sequence in checkOS() so centos (v7) is set.

BTW, quick workaround:
`$ export OS=centos`

**Comment by mrkuddlez** [comment]
The workaround worked great, thanks a ton both of you for the help!
:)
