### ISSUE TITLE
How to update from script?

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#481]
Once you have installed your VPN using this script. There are going to be many changes I'm sure. How are we supposed to update to the latest config changes made with the script, or are we expected to reinstall the vm everytime?

**Comment by r7l** [comment]
You pull the script from here and redo the setup (run the script) and hand out new credentials for your users. I don't think you need to reinstall a VM.

But it would actually be nice to have releases.

**Comment by ghost** [comment]
When you download it and run it a second time it only asks to add/remove users and maybe one more setting I can change. Does this mean there just been no updates, or am I doing something wrong?

**Comment by r7l** [comment]
The script does not have an update feature as far as i can see it. You need to pull a new version with Git or download it manually if you see it has been updated since your last download. I would suggest using Git as it clearly shows if there has been anything updated.

If you think anything important has been updated and you need to update your setup, you need to uninstall the existing setup (should be option 4 i think) and run the script again.

The last update was 21 days ago according to the commits: https://github.com/angristan/openvpn-install/commits/master

**Comment by ghost** [comment]
I think there's a bit of a misunderstanding here. I am using git, following the instructions. When there is an update if I run the script again is it going to update stuff or just ask me to add a new user as it does now? This is not a documented process.

**Comment by ghost** [comment]
Yeah there is no option 4 and i Just did a git pull. 3 options.

**Comment by r7l** [comment]
Just checked. Well, there are 4 for me but 4 would be "Exit". So it's the 3rd option. `Remove OpenVPN` but then i might be wrong about the update process.

I would do it like this as there is no other option for updates yet.

**Comment by angristan** [comment]
#179 #319 #430
