### ISSUE TITLE
Issue with Debian 10 <tls-crypt> empty

### ISSUE THREAD

**Issue by madprogrammerx** [angristan/openvpn-install#523]
Hi there,

first, thanks alot for your script, been using it several years now.

Now ive got issues using your script with debian 10.

When creating a new user the <tls-crypt> part is empty, so its not possible to import it in any openvpn client.

I think it has something todo with the line:
openvpn --genkey --secret /etc/openvpn/tls-crypt.key
in your script.

any workarounds here?

**Comment by angristan** [comment]
Hey, I just tried on a Digital Ocean droplet running Debian 10 and tls-crypt works fine. Could you send the whole output when running `bash -x openvpn-install.sh`?

**Comment by madprogrammerx** [comment]
[scout.txt](https://github.com/angristan/openvpn-install/files/3905623/scout.txt)

**Comment by madprogrammerx** [comment]
sure here is it^^

you see the problem in the last lines:
+ cat /etc/openvpn/tls-crypt.key
cat: /etc/openvpn/tls-crypt.key: Datei oder Verzeichnis nicht gefunden

File/directory not found

ive used a complete fresh debian 10 install inside a vm

**Comment by TheRealAstroboy** [comment]
Same here (AWS, Debian 10).
Old vpn profiles work (tls-auth) but new ones don't (tls-crypt).

After running "openvpn --genkey --secret /etc/openvpn/tls-auth.key" on my server, no more importation error with the openvpn client but handshake fail : 

Mon Feb 03 14:39:21 2020 MANAGEMENT: >STATE:1580737161,WAIT,,,,,,
Mon Feb 03 14:40:22 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Feb 03 14:40:22 2020 TLS Error: TLS handshake failed
Mon Feb 03 14:40:22 2020 SIGUSR1[soft,tls-error] received, process restarting
Mon Feb 03 14:40:22 2020 MANAGEMENT: >STATE:1580737222,RECONNECTING,tls-error,,,,,

**Comment by angristan** [comment]
@madprogrammerx the issue is here:

```
+ openvpn --genkey --secret /etc/openvpn/tls-crypt.key
openvpn-install.sh: Zeile 693: openvpn: Kommando nicht gefunden.
```

Something is wrong with your `$PATH` because we can see that OpenVPN is installed just above.

**Comment by Fox682** [comment]
I had the same problem, I think angristan is right the path is probably messed up, there's a weird issue where in Debian 10 if you run "su" vs "su -". Some programs will not run unless you run "su -" because the paths can be different. By default the /sbin and /usr/sbin paths are not part of the shell environment when you "su" to root. Workaround is to edit the /etc/login.defs and add "ALWAYS_SET_PATH yes". Otherwise use "su -". Or if you prefer not to modify this behavior you can make an alias in your .bashrc file `alias su='su -'`.

I ran the openvpn script and it installed but when I generated a certificate the `<tls-crypt>` section was empty. After running; `openvpn --genkey --secret /etc/openvpn/tls-auth.key` the file tls-crypt.key was now present in the openvpn directory (it was missing before!).
 
After running the key generating command the certificates now contain key material for the `<tls-crypt` section. I'd have to find some more time to do testing but I've got a sneaking suspicion that the "su" vs "su -" may be to blame.

**Comment by Fox682** [comment]
> After running the key generating command the certificates now contain key material for the `<tls-crypt` section. I'd have to find some more time to do testing but I've got a sneaking suspicion that the "su" vs "su -" may be to blame.

Yup, running the openvpn-install script works as expected without errors if you use `su -` to root on Debian 10 **before** running the script. Tested on a new VPS.

Angristan, I would say it's probably a good idea to put a blurb in the script for Debian 10. 

Something like: `WARNING: You MUST log in to root with 'su -' or the server setup will fail without further warnings!`

Been using this for a couple of years, bailed me out a few times. Your efforts here are very much appreciated, thank you!
