### ISSUE TITLE
Backup Possibility

### ISSUE THREAD

**Issue by A2116** [angristan/openvpn-install#569]
How can backup server and client settings and transfer it to another server? is it possible?

**Comment by randshell** [comment]
Try installing it using the script and then copy recursively `/etc/openvpn` from the old server to the new one to restore everything. Overwrite if asked and then restart openvpn service.

For clients backup the `.ovpn` files, but you don't need them on the server if this is what you ask.

**Comment by angristan** [comment]
Yep. Also update the hostname/IP on the clients if needed.

**Comment by berlusconi500** [comment]
Hi, today I made a backup of the "/etc/openvpn" folder and put it in a new installation. Everything works and old clients are able to talk to the server.
The problem is created when I try to create a new client through the "openvpn-install.sh" script. The latter is generated but not work. Inside the certificate the private key is missing.

Am I doing something wrong or isn't the script meant to do what I want?


EDIT:

My mistake. It all works. I had lost "openvpn / easy-rsa / easyrsa" execute permissions while copying
