### ISSUE TITLE
archlinux

### ISSUE THREAD

**Issue by openmotion** [angristan/openvpn-install#61]
it works in archlinux, but after reboot the openvpn server is not started, and i do not understand how to start it again ... is there a systemd service ?

the openvpn@server.service is in the directory : /etc/systemd/system/multi-user.target.wants/openvpn@server.service
and is empty

systemctl restart openvpn@server.service
Failed to restart openvpn@server.service: Unit openvpn@server.service not found.

thanks

**Comment by mattwelke** [comment]
I'm having trouble getting this to work on Arch too. My install script actually had an error saying it couldn't start the service. And I had to run the install script with ```sudo``` (otherwise it wouldn't start, it said I had to run it with sudo). I wonder if that has anything to do with it.

I notice when I import the profile into OpenVPN Connect on my Android phone that the profile has ```/autologin``` appended to the host I specified too.

**Comment by openmotion** [comment]
i resolved like this 
in the server.conf i add the full path to the certificates
then i execute : openvpnserver /etc/openvpn/server.conf

for the client i copy the ovpn file to something.conf in /etc/openvpn/client/ folder
then i enable and start the client service 
systemctl start openvpn-client@myclient.service

**Comment by mattwelke** [comment]
Hmm thanks for the tips. I ended up finding a solution where OpenVPN was encapsulated in a Docker image (https://github.com/kylemanna/docker-openvpn). It had some commands to run to set it up and then you were done and it was running, no matter which distro you were using.

**Comment by vahidshirvani** [comment]
I have the script running in docker. Please see https://github.com/vahidshirvani/openvpn-install
