### ISSUE TITLE
Client connection problem

### ISSUE THREAD

**Issue by tomnick** [angristan/openvpn-install#636]
Trying to connect with my client and getting the following error:
Unrecognized option or missing parameter(s) in vpn-keys/de/jesse_de.ovpn:18: block-outside-dns (2.3.10)
Options error: Unrecognized option or missing parameter(s) in vpn-keys/de/jesse_de.ovpn:23: tls-crypt (2.3.10)

My client data:
client
proto udp
explicit-exit-notify
remote ********* 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_sAfn02WmkFemG0ly name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3

**Comment by randshell** [comment]
What OS are you using to connect and what application? The [issue template](https://github.com/angristan/openvpn-install/blob/master/.github/ISSUE_TEMPLATE/bug-report-or-suport-request.md) isn't optional because it helps finding the issue.

> Options error: Unrecognized option or missing parameter(s) in vpn-keys/de/jesse_de.ovpn:23: tls-crypt (2.3.10)

Your client doesn't support tls-crypt. You can reinstall openvpn server, choose yes when asked to customize encryption settings and use tls-auth.

**Comment by angristan** [comment]
Great... I added issues templates and now people are giving even less details...

**Comment by angristan** [comment]
Solution: use OpenVPN 2.4
