### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by LDByteron** [angristan/openvpn-install#740]
The script worked very well for me on centOS 7, but is there a way to get openvpn 2.4.9 (wich is installed by the scipt with TLS 1.3 (openssl 1.1.1)

Thanks!

**Comment by randshell** [comment]
TLS 1.3 support starts from Centos 8, I would recommend to upgrade the OS instead of manually building and updating openvpn and openssl.

**Comment by LDByteron** [comment]
Tanks for your answer! 

 

I had openvpn on cent os 8 with tls 1.3 but I would like to do the 2nd factor with linotp (www.linotp.org <http://www.linotp.org> ) which has no way for installing on cent os 8 …. So I went back to cent os 7… ?

 

Von: randomshell <notifications@github.com> 
Gesendet: Dienstag, 13. Oktober 2020 21:22
An: angristan/openvpn-install <openvpn-install@noreply.github.com>
Cc: LDByteron <PC@Seils.info>; Author <author@noreply.github.com>
Betreff: Re: [angristan/openvpn-install] TLS 1.3 (#740)

 

TLS 1.3 support starts from Centos 8, I would recommend to upgrade the OS instead of manually building and updating openvpn and openssl.

**Comment by randshell** [comment]
Upon investigation, linotp is based on the old and not anymore in use python2.7. The incompatibility on Centos 8 comes from the fact that this version of the distro switched completely to python3.

You could compile the latest version of openvpn and the stable one of openssl to support TLS 1.3, but in the end linotp should switch to python3. You can try contacting them.

BTW I recommended not to compile manually at start to avoid the need of keeping openvpn and openssl up to date manually instead of relaying on the distro repository.
