### ISSUE TITLE
how can I make it work on udp and tcp at the same time

### ISSUE THREAD

**Issue by mercik** [angristan/openvpn-install#753]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mercik** [comment]
if possible, add this to the script

**Comment by randshell** [comment]
Assuming you did an IPv4 only installation with UDP:
- `cd /etc/openvpn`
- `cp server.conf server2.conf`
- edit the `proto` option in `server2.conf` to use TCP
- `systemctl enable openvpn@server2` and `systemctl restart openvpn@server2` if you use Debian or Ubuntu.
`systemctl enable openvpn-server@server2` and `systemctl restart openvpn-server@server2` if you use Fedora, CentOS or Arch. 
- duplicate the line containing UDP (it should be the last one) inside `/etc/iptables/add-openvpn-rules.sh` and change it to use TCP
- do the same with the file `/etc/iptables/rm-openvpn-rules.sh`
- `systemctl restart iptables-openvpn`

This should be all, let me know if it worked for you.

**Comment by mercik** [comment]
can I make one port tcp and udp

**Comment by randshell** [comment]
Yes you can, do the installation by choosing UDP and then follow the steps above to also make TCP work.

**Comment by Saya47** [comment]
@randomshell and @angristan Hello I have a question!
I did what was described but there's an issue, my client connects successfully but does NOT have internet access. What solved the issue was to stop the `openvpn@server` and only have `openvpn@server2` running, then the client had internet access, I was using 2 different ports btw (and I also removed `explicit-exit-notify` for the UDP config.
It'd be great if there was a way to run both TCP and UDP at the same time.
