### ISSUE TITLE
changes in openvpn 2.5

### ISSUE THREAD

**Issue by joksik** [angristan/openvpn-install#768]
new version openvpn 2.5 under linux abandoned used earlier
**user nobody
group noboy**
now openvpn add user openvpn and start services with this user so we can simple remove this two lines from server.conf

second change that i see in logs with warning is that now we dont use:
ncp-ciphers but data-ciphers and we can read on openvpn site in deprecated options that ncp-ciphers will be remove in openvpn 2.6 it is important to fix or this script will not work with next openvpn version

**Comment by randshell** [comment]
We already have #761 opened for OpenVPN 2.5, can you please comment there instead?

> now openvpn add user openvpn and start services with this user so we can simple remove this two lines from server.conf

The script supports multiple versions of OpenVPN and different Linux distributions, in my opinion is better to leave these options in the config for now.

> ncp-ciphers but data-ciphers and we can read on openvpn site in deprecated options that ncp-ciphers will be remove in openvpn 2.6 it is important to fix or this script will not work with next openvpn version

Thanks for reporting this.

I read [here](https://github.com/OpenVPN/openvpn/commit/342f9b78f107530f67581d6247d38af0792e4243) that it's not going to be removed anytime soon so it's very possible that it might take years. I think we can wait before changing this, also because the option is not compatible with versions older than 2.5 which was just released.

**Comment by TinCanTech** [comment]
> new version openvpn 2.5 under linux abandoned used earlier
> **user nobody group noboy**
> now openvpn add user openvpn and start services with this user

Openvpn has not done/does not do this but your distro may have.

> second change that i see in logs with warning is that now we dont use:
> ncp-ciphers but data-ciphers and we can read on openvpn site in deprecated options that ncp-ciphers will be remove in openvpn 2.6 it is important to fix or this script will not work with next openvpn version

Cipher negotiation will take care of this in all but the weirdest cases. 
https://community.openvpn.net/openvpn/wiki/CipherNegotiation

Also, Openvpn 2.3 is no longer supported, except for critical security updates.
https://community.openvpn.net/openvpn/wiki/SupportedVersions

**Comment by angristan** [comment]
Converted #761 to a discussion, please use it instead
