### ISSUE TITLE
Add user authentication for the private key

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#9]
Currently the script generates an all-in-one client configuration and does not ask for a password to decrypt the private key.

As this is a hardened OpenVPN install script, it would be nice a add an option to use a password when connecting to the VPN, to avoid anyone with the .ovpn file to be able to connect.

The modifications will have to be done [around here](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L409) with easy-rsa.

**Comment by ohunecker** [comment]
First, you have to expand the [menu for add or remove a user cert](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L88) with the following option:
`2) 
			echo ""
			echo "Tell me a name for the client cert"
			echo "Please, use one word only, no special characters"
			read -p "Client name: " -e -i client CLIENT
			cd /etc/openvpn/easy-rsa/
			./easyrsa build-client-full $CLIENT
			# Generates the custom client.ovpn
			newclient "$CLIENT"
			echo ""
			echo "Client $CLIENT added, certs available at ~/$CLIENT.ovpn"
			exit
			;;`

After that you can change the [default creation of a user cer](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L409)t with this:
`while :
	do
	clear
		echo "What type of cert do you want to create?"
		echo "   1) Create a cert without password for a new user"
		echo "   2) Create a cert with password for a new user"
		read -p "Select an option [1-2]: " option
		case $option in
			1) 
			./easyrsa build-client-full $CLIENT nopass
			exit
			;;
			2) 
			./easyrsa build-client-full $CLIENT
			exit
			;;
		esac
	done`

**Comment by rhbkweb** [comment]
On Nyr original script in order to generate a user key/cert with password he said that: "Just look at lines 84 and 217. If you remove nopass, it will simply ask for one during creation"

Does anyone knows what are the exact lines on this script?

**Comment by angristan** [comment]
Look at my post :)

**Comment by rhbkweb** [comment]
@Angristan 

From looking on your post it seems I must change the following 3 lines, correct?

409	./easyrsa build-server-full server nopass
410	./easyrsa build-client-full $CLIENT nopass
411	./easyrsa gen-crl

If yes, should I just remove the "nopass" on line 409 and 410 or further changes are needed? Thanks

**Comment by angristan** [comment]
Removing nopass from lines 409 and 410 should do it

**Comment by rhbkweb** [comment]
@Angristan 

I have tryed but when trying to connect to the OpenVPN server I can't get a connection. Bellow is the connection log. Do you have idea on where the problem is:

`Sun Jan 01 16:21:43 2017 OpenVPN 2.3.12 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKCS11] [IPv6] built on Aug 23 2016
Sun Jan 01 16:21:43 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Sun Jan 01 16:21:43 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.09
Sun Jan 01 16:21:43 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25341
Sun Jan 01 16:21:43 2017 Need hold release from management interface, waiting...
Sun Jan 01 16:21:44 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25341
Sun Jan 01 16:21:44 2017 MANAGEMENT: CMD 'state on'
Sun Jan 01 16:21:44 2017 MANAGEMENT: CMD 'log all on'
Sun Jan 01 16:21:44 2017 MANAGEMENT: CMD 'hold off'
Sun Jan 01 16:21:44 2017 MANAGEMENT: CMD 'hold release'
Sun Jan 01 16:22:05 2017 MANAGEMENT: CMD 'password [...]'
Sun Jan 01 16:22:05 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Jan 01 16:22:05 2017 Control Channel Authentication: tls-auth using INLINE static key file
Sun Jan 01 16:22:05 2017 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Jan 01 16:22:05 2017 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Jan 01 16:22:05 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sun Jan 01 16:22:05 2017 UDPv4 link local: [undef]
Sun Jan 01 16:22:05 2017 UDPv4 link remote: [AF_INET]XXX.XXX.XXX.XX:1194
Sun Jan 01 16:22:05 2017 MANAGEMENT: >STATE:1483287725,WAIT,,,
Sun Jan 01 16:22:05 2017 MANAGEMENT: >STATE:1483287725,AUTH,,,
Sun Jan 01 16:22:05 2017 TLS: Initial packet from [AF_INET]XXX.XXX.XXX.XX:1194, sid=23018a9e 84c577f0
Sun Jan 01 16:22:05 2017 VERIFY OK: depth=1, CN=ChangeMe
Sun Jan 01 16:22:05 2017 Validating certificate key usage
Sun Jan 01 16:22:05 2017 ++ Certificate has key usage  00a0, expects 00a0
Sun Jan 01 16:22:05 2017 VERIFY KU OK
Sun Jan 01 16:22:05 2017 Validating certificate extended key usage
Sun Jan 01 16:22:05 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Jan 01 16:22:05 2017 VERIFY EKU OK
Sun Jan 01 16:22:05 2017 VERIFY OK: depth=0, CN=server
Sun Jan 01 16:23:05 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Jan 01 16:23:05 2017 TLS Error: TLS handshake failed
Sun Jan 01 16:23:05 2017 SIGUSR1[soft,tls-error] received, process restarting
Sun Jan 01 16:23:05 2017 MANAGEMENT: >STATE:1483287785,RECONNECTING,tls-error,,
Sun Jan 01 16:23:05 2017 Restart pause, 2 second(s)
Sun Jan 01 16:23:07 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sun Jan 01 16:23:07 2017 UDPv4 link local: [undef]
Sun Jan 01 16:23:07 2017 UDPv4 link remote: [AF_INET]XXX.XXX.XXX.XX:1194
Sun Jan 01 16:23:07 2017 MANAGEMENT: >STATE:1483287787,WAIT,,,
Sun Jan 01 16:23:07 2017 MANAGEMENT: >STATE:1483287787,AUTH,,,
Sun Jan 01 16:23:07 2017 TLS: Initial packet from [AF_INET]XXX.XXX.XXX.XX:1194, sid=f6ad492b e0f51661
Sun Jan 01 16:23:07 2017 VERIFY OK: depth=1, CN=ChangeMe
Sun Jan 01 16:23:07 2017 Validating certificate key usage
Sun Jan 01 16:23:07 2017 ++ Certificate has key usage  00a0, expects 00a0
Sun Jan 01 16:23:07 2017 VERIFY KU OK
Sun Jan 01 16:23:07 2017 Validating certificate extended key usage
Sun Jan 01 16:23:07 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Jan 01 16:23:07 2017 VERIFY EKU OK
Sun Jan 01 16:23:07 2017 VERIFY OK: depth=0, CN=server`

**Comment by rhbkweb** [comment]
Nervermind... problem solved :)

**Comment by Kcchouette** [comment]
Can I know why this password will be useful?
For the server, one private client key equal a authentification (so something like a password)?

Oh, and I have some extra-question:
Can one .ovpn file be use by more than one person (or on more than one device) in the **same time**?

**Comment by angristan** [comment]
> Can I know why this password will be useful?

Without a password, anyone with the config file can connect to the VPN.

> Can one .ovpn file be use by more than one person (or on more than one device) in the same time?

Nope

**Comment by Kcchouette** [comment]
Ok thank you 😄

**Comment by blackwatercitadel** [comment]
@ohunecker i tried to following your post from above, just wasn't sure where to put your code {while : do clear echo "What type of cert do you want to create?" echo " 1) Create a cert without password for a new user" echo " 2) Create a cert with password for a new user" read -p "Select an option [1-2]: " option case $option in 1) ./easyrsa build-client-full $CLIENT nopass exit ;; 2) ./easyrsa build-client-full $CLIENT exit ;; esac done}

I also tried at a different time to just remove the "nopass" on line 409 and 410.

Is there anyway that you or @Angristan provide a script with the option for client password. Greatly appreciated.

**Comment by richardland** [comment]
As far as I can see removing "nopass" on line 409 and 410 will not work. The line nubers do not match current version of scipt, but more important:

only remove "nopass" on lines that contain "./easyrsa build-client-full ..."

In current script only two occurances; one that gets triggered on initial install and the one that gets triggered when adding extra clients.

**Comment by BenGamma** [comment]
With actual version of the script, to enable password authentication you have to remove the ```nopass``` attribute on both lines : 
https://github.com/Angristan/OpenVPN-install/blob/edbe4fed90841aebe7f1fecf95a9893eea19ab14/openvpn-install.sh#L419
and https://github.com/Angristan/OpenVPN-install/blob/edbe4fed90841aebe7f1fecf95a9893eea19ab14/openvpn-install.sh#L420

**Comment by joshuwahaus** [comment]
Is it possible yet to easily implement password auth of the key?

**Comment by orazioedoardo** [comment]
Perhaps I’m wrong but if we remove `nopass` from `./easyrsa build-server-full server nopass` the provided password (different from the client password) will be required each time the server is restarted.

**Comment by craig-mld** [comment]
You are right orasioedoardo, removing nopass from the server key does mean that the server passphrase is required on reboot.
We required passphrases on the user keys and on the CA key and removing nopass for both of these worked straight out the box.

```
./easyrsa init-pki
./easyrsa --batch build-ca
openssl dhparam -out dh.pem $DH_KEY_SIZE
./easyrsa build-server-full server nopass
./easyrsa build-client-full $CLIENT
EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
```

You will also need to remove it from the install client generation

```
./easyrsa build-client-full $CLIENT
# Generates the custom client.ovpn
newclient "$CLIENT"
```

There is also a problem with easyrsa 3.0.3 that pops up when you start using passphrases (https://github.com/OpenVPN/easy-rsa/commit/4ba461deeb4db4af4433d92ff0d6d8e52ab8011a).  I fixed this too:

```
# Fix the IF typo in EasyRSA
cp easyrsa easyrsa-original
sed -i -e '644,645d;944,945d' easyrsa
sed -i '643 a if [ "$crt_type" = 'server' ]; then' easyrsa
sed -i '942 a if [ $? -eq 0 ]; then' easyrsa
```

This all works well for me on Ubuntu 16.04.  I haven't tested any other OSes yet.

**Comment by ghost** [comment]
@craig-mld I don't see any reasons to request a password also on the CA, btw a pull request for an encrypted private key support will be great.

**Comment by angristan** [comment]
Sorry for the delay, everyone! Finally added the feature in #160.
